### ISSUE TITLE
Cannot connect to device

### ISSUE THREAD

**Issue by rugk** [prey/prey-android-client#114] opened 2016-05-15 10:00 UTC
When trying to login from my device I get this error message:

> **We have a situation!** [nice title BTW :laughing: ]
> 
> Prey couldn't connect to the web Control Panel.
> Check your settings and try again.

I have AFWall+ installed, but Prey is whitelisted.

**Comment by raliste** [comment] 2016-05-15 22:59
Hi @rugk 

You should try the Connectivity Test at http://solid.preyproject.com/test - please send us a screenshot of the result.

You should also make sure that all connections to solid.preyproject.com and clients1.preyproject.com are whitelisted for ports 80 and 443.

**Comment by rugk** [comment] 2016-05-16 11:52
Everything is green.
In some firewall logs on my phone I can also see Prey connecting...

But am I right that this can't be a password error, because I would get a different error message?

![preyconnect](https://cloud.githubusercontent.com/assets/11966684/15288739/54628d8c-1b6d-11e6-9324-ff18bd7f8b67.png)

**Comment by camilaburgos** [comment] 2016-07-08 19:23
Hello @rugk. Is this still happening?

**Comment by rugk** [comment] 2016-07-08 20:34
Yes, however now I also cannot login into the web panel anymore. And as I am using a password manager the password is certainly not wrong.

**Comment by dza89** [comment] 2016-07-09 19:05
@rugk 
I had the exact same problem, total shot in the dark... is it possible that you already have three (old) devices attached to your account? Prey seems to display this message when you're account is full.

**Comment by raliste** [comment] 2016-07-09 21:47
Could you also try the connectivity test at
https://solid.preyproject.com/test ?



On Sat, Jul 9, 2016 at 3:05 PM, dza89 <notifications@github.com> wrote:

> @rugk <https://github.com/rugk>
> I had the exact same problem, total shot in the dark... is it possible
> that you already have three (old) devices attached to your account? Prey
> seems to display this message when you're account is full.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/prey/prey-android-client/issues/114#issuecomment-231550379>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXvR3RqKK7HgmaNo9noEgWl1EaERMm9ks5qT_EKgaJpZM4IezGu>
> .
>



-- 
Rodrigo Aliste P.

**Comment by dza89** [comment] 2016-07-10 12:29
IP Trace: 62.58.242.133, 107.178.244.155, 130.211.1.7
User Agent: Mozilla/5.0 (Linux; Android 6.0.1; E5823 Build/32.2.A.0.224) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Mobile Safari/537.36
profile.json completed with trace preyfrontend, @vip_endpoints (252 ms)
signup.json completed with trace preyfrontend, @vip_endpoints (252 ms)
Latency Test: 362 ms (20.67, 14.32)


It's fixed now, after removing a device, the message just doesn't match the problem. (Prey couldnt connect to the webcontrolpanel, please check your settings and try again)

**Comment by heinhuiz** [comment] 2016-07-17 09:52
Hi, I'm having this same problem but with a twist: I can't reach solid.preyproject.com/test, neither from my phone or from my desktop PC. On both Firefox reports: "The page isn't redirecting properly".
I can login to Prey from my PC though, just not from my phone.

**Comment by helenst** [comment] 2016-12-28 10:59
Same problem here - from the message it is really not obvious what the problem is - especially as I was just adding a phone that was already listed but had an OS reinstall. Removing the old device solved the problem. An error message that says what the problem is would have been helpful!

**Comment by jonaskrauspe** [comment] 2017-01-06 10:27
I just tried the Prey Connectivity test and received these two errors:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
profile.json error
signup.json error
Latency Test: 308 ms (78.96, 54.72)

Any idea how to solve? I've already enabled every script etc. on the Prey page.
Device is locating itself on Google Maps.

**Comment by wezko** [comment] 2017-04-04 23:53
Same here. Installed app, cannot connect to web panel.
http test: profile json error, signup json error
https: all green

**Comment by ceblack** [comment] 2017-04-09 02:47
I'm having the same problem from multiple networks on both my PC and Android devices. No firewalls/proxies/VPNs/etc, and from my Android device the T-Mobile 4G network

**Comment by tyrope** [comment] 2017-08-30 18:39
I recently change my mother's devices from my account to a new account on her email. When trying to add either of her tablets they give a "device cannot be added to this account. Check email and password [502]"

The above linked webpage gives:

```Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds```
I tried again 5min later... 2hr later... control panel logs in fine on the same device same WiFi.

**Comment by CAIIIA** [comment] 2017-09-15 08:07
Deleting device from web page helped me. It was same device after hardreset couldn't connect with error "Prey couldn't connect to the web Control Panel."

**Closed** 2019-11-24 14:34 UTC
